services:
  quickbite-db:
    image: postgres:15-alpine
    container_name: quickbite-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=quickbite_user_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - quickbite-net

  quickbite-user:
    build: ../exercise_01/user-service
    image: quickbite-user-service:latest
    container_name: quickbite-user
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://quickbite-db:5432/quickbite_user_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - quickbite-net
    depends_on:
      - quickbite-db

  quickbite-restaurant:
    build: ../exercise_01/restaurant-service
    image: quickbite-restaurant-service:latest
    container_name: quickbite-restaurant
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:postgresql://quickbite-db:5432/restaurant_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - quickbite-net
    depends_on:
      - quickbite-db

  quickbite-order:
    build: ../exercise_01/order-service
    image: quickbite-order-service:latest
    container_name: quickbite-order
    ports:
      - "8083:8083"
    environment:
      - SERVER_PORT=8083
      - SPRING_DATASOURCE_URL=jdbc:postgresql://quickbite-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - quickbite-net
    depends_on:
      - quickbite-db

  quickbite-notification:
    build: ../exercise_01/notification-service
    image: quickbite-notification-service:latest
    container_name: quickbite-notification
    ports:
      - "8084:8084"
    environment:
      - SERVER_PORT=8084
      - SPRING_DATASOURCE_URL=jdbc:postgresql://quickbite-db:5432/notification_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - quickbite-net
    depends_on:
      - quickbite-db

networks:
  quickbite-net:
    external: true
