server {
    listen 80;
    server_name localhost;

    location /users/ {
        # Sử dụng DNS name của service 'user_service' trong mạng Docker Compose
        proxy_pass http://user_service:8081/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /products/ {
        # Sử dụng DNS name của service 'product_service' trong mạng Docker Compose
        proxy_pass http://product_service:8082/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        return 200 'StoreX API Gateway is running. Available endpoints: /users/, /products/\n';
        add_header Content-Type text/plain;
    }
}
