spring.application.name=banking-app

server.port=8080

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/banking_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-Banking
logging.level.com.zaxxer.hikari=INFO
logging.level.com.example.banking=INFO